### ISSUE TITLE
User Groups don't appear when using xAdmin2

### ISSUE THREAD

**Issue by afuckingstoner** [Weol/WUMA#48]
When using xAdmin2, the usergroups I created do not appear.
xAdmin2 also does have CAMI implemented

![wuma1](https://user-images.githubusercontent.com/65723658/83426157-a01a1d80-a426-11ea-9f54-d2cd3750c7be.jpg)
![wuma2](https://user-images.githubusercontent.com/65723658/83426159-a0b2b400-a426-11ea-9514-1380deeb8f68.jpg)

**Comment by Weol** [comment]
Hmm, it might be difficult to fix this since its a paid addon. We can at least try to narrow it down. The CAMI function that is used to fetch usergroups is `CAMI.GetUsergroups()`. If you can run `lua_run PrintTable(CAMI.GetUsergroups())` in the server console then it will print all of the usergroups registered in CAMI. Please paste the output here,

**Comment by Weol** [comment]
As far as I can tell, xAdmin2 is not implementing CAMI properly. CAMI.GetUsergroups() should return all registered usergroups, but its not with xAdmin2.
