### ISSUE TITLE
Issue with resticting simfphys

### ISSUE THREAD

**Issue by QueenDraco** [Weol/WUMA#53]
i cant restrict any of the simfphys stuff

**Comment by Weol** [comment]
You can restrict them, the problem is that they don't show up in the list of items. However, if you right-click the car you want to restrict and press "Copy to clipboard" and paste it into the search bar you can still restrict it. 

If the list of items is empty when you search for something, then you can still press "Restrict" and it will restrict anything that is entered in the search textbox.
